# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reranker.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'reranker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ereranker.proto\x12\x08reranker\"1\n\rRerankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tdocuments\x18\x02 \x03(\t\"C\n\x0cRerankResult\x12\x16\n\x0eoriginal_index\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t\"9\n\x0eRerankResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.reranker.RerankResult2N\n\rRerankService\x12=\n\x06Rerank\x12\x17.reranker.RerankRequest\x1a\x18.reranker.RerankResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reranker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RERANKREQUEST']._serialized_start=28
  _globals['_RERANKREQUEST']._serialized_end=77
  _globals['_RERANKRESULT']._serialized_start=79
  _globals['_RERANKRESULT']._serialized_end=146
  _globals['_RERANKRESPONSE']._serialized_start=148
  _globals['_RERANKRESPONSE']._serialized_end=205
  _globals['_RERANKSERVICE']._serialized_start=207
  _globals['_RERANKSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
